[connections.snowflake]
account = "RM33789"
user = "bambooorgan"
password = "June71977"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
